language: node_js
cache: npm
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: XrmL8MfQisn0t4ic6q+/5zc3MsquQyggbYfTHEessUm4SWCkb77k+ZbJMJNDlzadnvvvfV5WpK42lHWMrF6VaKcrmDZuE2q2dExmRsePJG/yId0LyTGTNmKC6pjGewZ4NNMJcsMJ4vxEBFwUadSPN7LdY0xmGF/ru0Ypi57Ofg4GkasNR2ZtAtS4IGIYoI/IQLfY2D3is/sU0/UhGNGJN5l/YEHob0r8qi9VjgK9toYPwQYgjUS86n+EtGAlacIpxAY3CkTVjh6JEAoU+c9UhFcbAeboZSfxvTGoma34mKAfmBCcVAFDxRzQOrvrSFBvNKZZLw34zVhivd/GMit+FSbaYKC8ZRkGppor/ONPATlJXTRKPScoo6sm//dxKdCkzjRmlSKpu7senpip0bArm9PazKDZkpDORU3s8q2sPvJpwWE/IdR+q6EixdKYIxZlBFuXDFYYg07Mjw414JVDiAfaqjlw11tthtRRnZa9jxpPy5KeM9sSGoNfT1B2PyQF4O06f6YVkG7BocHjWJSr3ItBjAHyDavUDKP1KbX7Nc0zW3ahYWBGOgBkIfWVyI5CQ4U4umOJ/Zy5YMx1gHBgpBEd/eLRWm0gxkvHZDcwh4IO5QEwaJT0YEiiQhL8Dj54oKLu+B4UjpttaMQ3iKGMOVFfTWY+M7l989Ft2K3R+lg=
